### ISSUE TITLE
Missing plugin should warn instead of error

### ISSUE THREAD

**Issue by simonvh** [vanheeringen-lab/genomepy#108] opened 2020-06-12 06:57 UTC
I still had `sizes` listed as a plugin. In this case genomepy will crash with an error. It would probably be better if there's just a warning printed if a plugin is unknown.

**Comment by siebrenf** [comment] 2020-06-12 12:27
Could you give a reproducible example?

I thought this would be an easy fix, but I cant reproduce the error even! I added sizes to the config file, and it gets listed with `genomepy plugin list` and `genomepy config show`. I can search and download genomes, alter other plugins, but no error :o

**Comment by siebrenf** [comment] 2021-01-29 16:28
Closing for now

**Closed by siebrenf** 2021-01-29 16:28 UTC
